# -*- coding: utf-8 -*-
"""AI ORBITAL FORENSICS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F1ZVBDl4lXBFEI4R8yeVa6ihaJXN3GUT

1. **DATASET** **CREATION**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import time

from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier

np.random.seed(42)

MU = 398600        # Earth gravitational parameter (km³/s²)
R_EARTH = 6371.0   # Earth mean radius (km)

samples_per_sat = 1000

# Real parent satellites — accurate orbital parameters
# (a, e, i, raan, argp) where argp = argument of perigee ω
satellites = {
    0: {"a": R_EARTH + 477,  "e": 0.002, "i": 82.5, "raan": 100, "argp": 45},   # Cosmos-1408
    1: {"a": R_EARTH + 850,  "e": 0.001, "i": 98.8, "raan": 300, "argp": 200},  # Fengyun-1C
    2: {"a": R_EARTH + 790,  "e": 0.003, "i": 86.4, "raan": 140, "argp": 90},   # Iridium-33
    3: {"a": R_EARTH + 790,  "e": 0.010, "i": 74.0, "raan": 170, "argp": 120},  # Cosmos-2251
    4: {"a": R_EARTH + 850,  "e": 0.008, "i": 51.4, "raan": 60,  "argp": 280},  # Breeze-M DEB
}

satellite_names = {
    0: "COSMOS-1408 (Russia ASAT, 2021)",
    1: "FENGYUN-1C (China ASAT, 2007)",
    2: "IRIDIUM-33 (Iridium-Cosmos collision, 2009)",
    3: "COSMOS-2251 (Iridium-Cosmos collision, 2009)",
    4: "BREEZE-M DEB (Proton-M explosion, 2012)",
}

data = []
for sat_id, params in satellites.items():
    for _ in range(samples_per_sat):
        a    = params["a"]    + np.random.normal(0, 600)
        e    = np.clip(params["e"] + np.random.normal(0, 0.06), 0, 0.99)
        i    = params["i"]    + np.random.normal(0, 10)
        raan = (params["raan"] + np.random.normal(0, 35)) % 360
        argp = (params["argp"] + np.random.normal(0, 45)) % 360  # ω: debris clusters near parent ω

        n    = np.sqrt(MU / max(a, 6400) ** 3)

        data.append([a, e, i, raan, argp, n, sat_id])

df = pd.DataFrame(
    data,
    columns=["semi_major_axis", "eccentricity", "inclination",
             "raan", "arg_perigee", "mean_motion", "target"]  # arg_perigee = ω

)

print("Dataset shape:", df.shape)
print("\nClass distribution:\n", df["target"].value_counts())
print("\nSample data:")
print(df.head())

"""2. **EXPLORATORY DATA ANALYSIS**"""

print("\n--- Dataset Info ---")
print(df.info())
print("\n--- Descriptive Statistics ---")
print(df.describe())

# Histograms
df.drop("target", axis=1).hist(figsize=(14, 8), bins=30, edgecolor="black")
plt.suptitle("Feature Distributions")
plt.tight_layout()
plt.show()

# Pairplot (using a sample to speed it up)
sns.pairplot(df.sample(500, random_state=42), hue="target", diag_kind="kde")
plt.suptitle("Pairplot of Orbital Features by Parent Satellite", y=1.02)
plt.show()

"""3. **PREPROCESSING**"""

X = df.drop("target", axis=1)   # 6 features: a, e, i, raan, arg_perigee, n
y = df["target"]

print("Features used:", list(X.columns))
# → ['semi_major_axis', 'eccentricity', 'inclination',
#     'raan', 'arg_perigee', 'mean_motion']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)

print(f"\nTrain size: {X_train.shape[0]} | Test size: {X_test.shape[0]}")

"""4. **MODEL TRAINING**"""

# RANDOM FOREST TRAINING

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print(" Random Forest Results")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("\nClassification Report:\n", classification_report(y_test, y_pred_rf))

# SVM TRAINING

from sklearn.svm import SVC

svm = SVC(probability=True, random_state=42)
svm.fit(X_train, y_train)

y_pred_svm = svm.predict(X_test)

print(" SVM Results")
print("Accuracy:", accuracy_score(y_test, y_pred_svm))
print("\nClassification Report:\n", classification_report(y_test, y_pred_svm))

# KNN TRAINING

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

y_pred_knn = knn.predict(X_test)

print(" KNN Results")
print("Accuracy:", accuracy_score(y_test, y_pred_knn))
print("\nClassification Report:\n", classification_report(y_test, y_pred_knn))

# XGBOOST TRAINING


from xgboost import XGBClassifier

xgb = XGBClassifier(eval_metric='mlogloss', random_state=42, verbosity=0)
xgb.fit(X_train, y_train)

y_pred_xgb = xgb.predict(X_test)

print("XGBoost Results")
print("Accuracy:", accuracy_score(y_test, y_pred_xgb))
print("\nClassification Report:\n", classification_report(y_test, y_pred_xgb))

# MODEL COMPARISON

print("\n Model Comparison")

print(f"Random Forest: {accuracy_score(y_test, y_pred_rf):.4f}")
print(f"SVM:           {accuracy_score(y_test, y_pred_svm):.4f}")
print(f"KNN:           {accuracy_score(y_test, y_pred_knn):.4f}")
print(f"XGBoost:       {accuracy_score(y_test, y_pred_xgb):.4f}")

"""5. **HYPERPARAMETER TRAINING**"""

# RANDOM FOREST

from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import accuracy_score

param_rf = {
    "n_estimators": [100, 200, 300],
    "max_depth": [None, 10, 20],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2],
    "max_features": ['sqrt', 'log2']
}

rf_search = RandomizedSearchCV(
    RandomForestClassifier(random_state=42),
    param_distributions=param_rf,
    n_iter=10,
    cv=3,
    n_jobs=-1,
    random_state=42,
    verbose=1
)

rf_search.fit(X_train, y_train)

# Best model
rf = rf_search.best_estimator_

print("\n Best RF Parameters:", rf_search.best_params_)

# Evaluate tuned model immediately
y_pred_rf = rf.predict(X_test)

print("\n Tuned Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))

# XGBoost  (FIX: was labelled "KGB" in original code)
param_xgb = {
    "n_estimators":  [100, 200],
    "max_depth":     [3, 6, 10],
    "learning_rate": [0.01, 0.1]
}
xgb_search = RandomizedSearchCV(
    XGBClassifier(eval_metric="mlogloss", random_state=42, verbosity=0), param_xgb,
    n_iter=10, cv=3, random_state=42
)
xgb_search.fit(X_train, y_train)
xgb = xgb_search.best_estimator_
print("Best XGB params:", xgb_search.best_params_)

# Evaluate tuned models
print("\n--- After Tuning ---")
for name, model in [("RF (tuned)", rf), ("SVM", svm), ("KNN", knn), ("XGB (tuned)", xgb)]:
    acc = accuracy_score(y_test, model.predict(X_test))
    print(f"{name}: {acc:.4f}")

"""7. **ENSEMBLE VOTING CLASSIFIER**"""

voting_model = VotingClassifier(
    estimators=[("rf", rf), ("svm", svm), ("knn", knn), ("xgb", xgb)],
    voting="soft"
)
voting_model.fit(X_train, y_train)

y_pred = voting_model.predict(X_test)
print("\n--- Voting Ensemble ---")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=list(satellite_names.values())))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(9, 7))
sns.heatmap(
    cm, annot=True, fmt="d", cmap="Blues",
    xticklabels=[f"Sat {i}" for i in range(5)],
    yticklabels=[f"Sat {i}" for i in range(5)]
)
plt.title("Confusion Matrix — Voting Ensemble")
plt.xlabel("Predicted Parent Satellite")
plt.ylabel("Actual Parent Satellite")
plt.tight_layout()
plt.show()

"""8. **Real-Time Debris Stream Simulation**"""

def generate_fragment():
    """Simulate an incoming debris fragment from a random parent satellite."""
    sat_id = np.random.choice(list(satellites.keys()))
    p = satellites[sat_id]
    a    = p["a"]    + np.random.normal(0, 600)
    e    = np.clip(p["e"] + np.random.normal(0, 0.06), 0, 0.99)
    i    = p["i"]    + np.random.normal(0, 10)
    raan = (p["raan"] + np.random.normal(0, 35)) % 360

    argp = (p["argp"] + np.random.normal(0, 45)) % 360  # argument of perigee ω

    n    = np.sqrt(MU / max(a, 6400) ** 3)

    return [a, e, i, raan, argp, n], sat_id   # 6-feature vector matches X.columns


model = voting_model

print("\n--- Real-Time Debris Attribution ---")
for step in range(5):
    fragment, true_id = generate_fragment()


    df_new = pd.DataFrame([fragment], columns=X.columns)  # arg_perigee at index 4

    scaled  = scaler.transform(df_new)

    probs = model.predict_proba(scaled)[0]
    pred  = np.argmax(probs)

    print(f"\n  Incoming Debris #{step + 1}")
    print("-" * 50)
    for j, p in enumerate(probs):
        print(f"  {satellite_names[j]:<45} {p * 100:.2f}%")

    print(f"\n  Predicted : {satellite_names[pred]}")
    print(f"  Confidence: {max(probs) * 100:.2f}%")

    if max(probs) < 0.5:
        print("  [!] Low confidence — possible inter-cluster ambiguity")

    top2 = np.argsort(probs)[-2:][::-1]
    print("  Top 2 candidates:")
    for idx in top2:
        print(f"    {satellite_names[idx]}: {probs[idx] * 100:.2f}%")

    time.sleep(1)

"""9. **UNKNOWN DEBRIS PREDICTION**"""

# ─────────────────────────────────────────────────────────────────
# arg_perigee = 50° is physically motivated: fragments near
# Cosmos-1408 cluster around ω ≈ 45° (the parent's arg_perigee).
# Supplying a realistic ω tightens the attribution probability.
# ─────────────────────────────────────────────────────────────────
unknown_debris = pd.DataFrame([{
    "semi_major_axis": R_EARTH + 510,   # ~510 km altitude → LEO
    "eccentricity":    0.005,
    "inclination":     80.0,            # high inclination → Cosmos-1408 region
    "raan":            110.0,

    "arg_perigee":     50.0,            # ω ≈ 45° for Cosmos-1408 → strong forensic signal

    "mean_motion":     np.sqrt(MU / (R_EARTH + 510) ** 3)
}])

scaled_unknown = scaler.transform(unknown_debris)

prediction    = model.predict(scaled_unknown)[0]
probabilities = model.predict_proba(scaled_unknown)[0]

print("\n" + "=" * 55)
print("UNKNOWN DEBRIS ATTRIBUTION REPORT")
print("=" * 55)
print(f"Predicted Origin: {satellite_names[prediction]}\n")
print("Confidence Breakdown:")
for j, prob in sorted(enumerate(probabilities), key=lambda x: -x[1]):
    bar = "█" * int(prob * 40)
    print(f"  {satellite_names[j]:<45} {bar:<40} {prob * 100:.2f}%")

"""10. COMPARISON CHARTS"""

# ================================
# MODEL COMPARISON BAR CHART
# ================================

import matplotlib.pyplot as plt

models = ["Random Forest", "SVM", "KNN", "XGBoost", "Voting"]

accuracies = [
    accuracy_score(y_test, rf.predict(X_test)),
    accuracy_score(y_test, svm.predict(X_test)),
    accuracy_score(y_test, knn.predict(X_test)),
    accuracy_score(y_test, xgb.predict(X_test)),
    accuracy_score(y_test, voting_model.predict(X_test))
]

plt.figure(figsize=(8,5))
plt.bar(models, accuracies)

plt.title("Model Performance Comparison")
plt.ylabel("Accuracy")
plt.xlabel("Models")

# Annotate values
for i, v in enumerate(accuracies):
    plt.text(i, v + 0.01, f"{v:.2f}", ha='center')

plt.ylim(0, 1.1)
plt.show()